#---
#version: '1.0'
# declaration of version is optional since docker 19.03 + (native to ubuntu 20.04)

services:
  ros2cs:
    working_dir: /home/${projectName}
    build:
      context: .
      dockerfile: Dockerfiles/ros2cs_ws.dockerfile
      target: bng_on_vehicle
      args:
        TAG: latest
        PROJECT_NAME: ${projectName}
        ROS_DISTRO: ${rosdistro}

    environment:
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics,display"
      - "DISPLAY=${DISPLAY}"
      - "XAUTHORITY=/tmp/.docker.xauth"
      - "QT_X11_NO_MITSHM=1"
      - "ROS_DOMAIN_ID=${domain_id}"
    # simulation, logging and debug are true/false env variables.
    command: ./scripts/compose_up_cmd.sh -s ${simulation} -d ${debug} -l ${logging}
    volumes:
      - ./src:/home/${projectName}/src
      - ./scripts:/home/${projectName}/scripts
      - ./rosbags:/home/${projectName}/rosbags
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/tmp/.docker.xauth:ro
      - /dev/shm:/dev/shm
      - ./log:/home/${projectName}/log
      # FIXME: Only uncomment these to speed things up.
      #- ./build:/home/${projectName}/build
      #- ./install:/home/${projectName}/install
      # For logging to the dsu0 RAID array on the car computer
      - /mnt:/mnt
